### ISSUE TITLE
borges pack fails with invalid delta error

### ISSUE THREAD

**Issue by smola** [src-d/borges#314] opened 2018-08-08 17:29 UTC
Reported by @jjhenkel on Slack:

```
[2018-08-07T21:48:13.029042275Z] ERROR error pushing changes to rooted repository endpoint=git://github.com/google/guava.git error=push to rooted repo db3929bd79ef57f8da40515b663f40200a941fa8 failed: invalid delta
```

Happens on:

```
git://github.com/thx/RAP.git
git://github.com/getlantern/lantern.git
git://github.com/google/guava.git
```

The user tested both on latest master and v0.16.2. Running on `golang:1.10.3-stretch` Docker container.

I could not reproduce this running `borges pack` from scratch. Running it twice on Guava does not fail either.

I initially thought this could be related to a nasty fork and creating a packfile on push, but note that for the failing root on guava (`db3929bd79ef57f8da40515b663f40200a941fa8.siva`) was not even created. So there was no previous fork on that specific root. Maybe in one of the others.

**Comment by jfontan** [comment] 2018-11-14 16:28
Clone does not detect when the connection was closed prematurely and can be the cause of these errors.

**Comment by jfontan** [comment] 2018-12-07 13:50
This is fixed in go-git. Will be added to borges after a new go-git release.

**Comment by ajnavarro** [comment] 2018-12-19 11:00
@jfontan this is not blocked anymore, right? I think we have new go-git version available

**Comment by jfontan** [comment] 2018-12-19 17:12
It's still blocked, latest release still does not have the changes needed:

https://github.com/src-d/go-git/compare/v4.8.1...master

**Closed** 2019-02-28 19:01 UTC
Labels: blocked, bug
