### ISSUE TITLE
Consumer: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by bzz** [src-d/borges#88] opened 2017-07-04 07:39 UTC
On https://github.com/snowballstem/snowball-website Borges panics, most probably due to go-git

```
t=2017-07-01T11:53:40+0000 lvl=dbug msg="job started" module=borges WorkerID=16 RepositoryID=015cfd9f-846b-dd0b-23c6-f2098939fa91 caller=consumer.go:44
t=2017-07-01T11:53:40+0000 lvl=dbug msg="repository model obtained" job=015cfd9f-846b-dd0b-23c6-f2098939fa91 status=pending last-fetch=nil references=0 caller=archiver.go:93
t=2017-07-01T11:53:40+0000 lvl=dbug msg="endpoint selected" job=015cfd9f-846b-dd0b-23c6-f2098939fa91 endpoint=git://github.com/snowballstem/snowball-website.git caller=archiver.go:100
t=2017-07-01T11:53:40+0000 lvl=dbug msg="local temporary directory created" job=015cfd9f-846b-dd0b-23c6-f2098939fa91 temp-path=local_repos/015cfd9f-846b-dd0b-23c6-f2098939fa91/1498910020147732856 caller=archiver.go:109
t=2017-07-01T11:53:40+0000 lvl=dbug msg="local repository created" job=015cfd9f-846b-dd0b-23c6-f2098939fa91 caller=archiver.go:116
t=2017-07-01T11:53:43+0000 lvl=dbug msg="changes obtained" job=015cfd9f-846b-dd0b-23c6-f2098939fa91 roots=1 caller=archiver.go:143
panic: runtime error: index out of range

goroutine 3053 [running]:
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.PatchDelta(0xcbfda40000, 0x2d0000, 0x3ffe00, 0xca51047862, 0x3, 0x1e59e, 0x0, 0xd0c280, 0xc4728c3a00)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/patch_delta.go:60 +0x5b3
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.ApplyDelta(0xd0c280, 0xc4728c3900, 0xd0c280, 0xc4728c3a00, 0xca51026000, 0x21865, 0x3fe00, 0xd5e718, 0x9f9340)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/patch_delta.go:33 +0x149
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).fillOFSDeltaObjectContent(0xc4202aff60, 0xd0c280, 0xc4728c3900, 0xc, 0xc5f3009160, 0xc4202afbd8, 0x1)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:382 +0x202
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).decodeByHeader(0xc4202aff60, 0xc4728c38c0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:279 +0x3d6
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).DecodeObject(0xc4202aff60, 0xd0c280, 0xc6d5a61400, 0x0, 0x0)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:214 +0x66
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).decodeObjects(0xc4202aff60, 0x1eff, 0x0, 0x0)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:155 +0x40
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).doDecode(0xc4201def60, 0xa5caf0, 0xc4201def60)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:145 +0x103
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).Decode(0xc4202aff60, 0x0, 0x0, 0xc400000000, 0x0, 0x0)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:129 +0xa1
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit.(*PackWriter).buildIndex(0xc579c5ea00)
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/writers.go:64 +0xc5
created by github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit.newPackWrite
        /root/go/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit/writers.go:52 +0x3b5
```

**Comment by bzz** [comment] 2017-07-04 08:03
Tried to reproduce
 -  `git.PlainClone` works well
 -  it seems to be failing on [Archiver.pushChangesToRootedRepositories()](https://github.com/src-d/borges/blob/6bafcd0325fcee5d646e8454f6018f5491229c3b/archiver.go#L259)

**Comment by bzz** [comment] 2017-07-04 10:42
Could not reproduce this locally on Borges consumer/producer \w this single repo :/

After a conversation with @smola  - it seems that this might be quite know to @ajnavarro  🐛 in `go-git`

**Comment by bzz** [comment] 2017-07-04 13:22
I tried to add a workaround for this in Borges, that would recover from such panics and just skip those repos. 

But according to https://github.com/golang/go/wiki/PanicAndRecover#panic it seems not to be possible, due to panic originating in go-git goroutine :/

> https://github.com/golang/go/wiki/PanicAndRecover#panic

**Comment by bzz** [comment] 2017-07-04 13:52
Reproducible short example [top2000-continue408.logs.txt](https://github.com/src-d/borges/files/1122267/top2000-continue408.logs.txt)

**Comment by bzz** [comment] 2017-07-04 16:53
To be able to proceed, I ~worked~ hacked around around it in https://github.com/src-d/go-git/blob/master/storage/filesystem/internal/dotgit/writers.go#L56 with

```go
	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("Recovered from panic: %v\n", r)
			w.result <- r.(error)
		}
	}()
```

**Comment by smola** [comment] 2017-07-06 09:36
This might be produced by go-git writing to the same temp packfile on multiple repositories. This would be fixed by https://github.com/src-d/go-billy-siva/pull/12 once it's applied to `src-d/core-retrieval`,

**Comment by ajnavarro** [comment] 2017-07-11 14:17
I am not able to reproduce this issue using Borges master version. Closing it. Feel free to open if the error appears again.

**Closed by ajnavarro** 2017-07-11 14:17 UTC
Labels: bug
